#!/usr/bin/env php
<?php

chdir(dirname(__FILE__));
require_once(dirname(__FILE__) . '/config/ProjectConfiguration.class.php');
include(sfCoreAutoload::getInstance()->getBaseDir() . '/command/cli.php');
