hello_world:
  url:   /hello_world/:username
  param: { module: hello_world, action: index }

user_list:
    url:   /user/user_list
    param: { module: user, action: userList }

sign_in:
    url:   /user/sign_in
    param: { module: user, action: signIn }

log_out:
    url:   /user/log_out
    param: { module: user, action: logOut }

homepage:
  url:   /
  param: { module: user, action: signIn }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
