hello_world:
  url:   /hello_world/:username
  param: { module: hello_world, action: index }

user_list:
    url:   /user/user_list
    param: { module: user, action: userList }

homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
