helloworld:
  url:   /hello_world/:username
  param: { module: hello_world, action: index }

homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
