user_profile:
    url:   /user/user_profile
    param: { module: user, action: userProfile }

user_list:
    url:   /user/user_list
    param: { module: user, action: userList }

login:
    url:   /user/login
    param: { module: user, action: login }

log_out:
    url:   /user/log_out
    param: { module: user, action: logOut }

homepage:
  url:   /
  param: { module: user, action: login }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
