default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, main.css]

  javascripts:    [jquery-3.2.1.js, bootstrap.min.js]

  has_layout:     true
  layout:         layout
