logInSuccess:
  metas:
    title: Вход

registrationSuccess:
  metas:
    title: Регистрация

userListSuccess:
  metas:
    title: Список пользователей
  javascripts: [UserListLoader.js, Popup.js, main.js]

editUserSuccess:
  metas:
    title: Редактирование пользователя
  javascripts: [UserListLoader.js, Popup.js, main.js]

userProfileSuccess:
  metas:
    title: Профиль