logInSuccess:
  metas:
    title: Вход

registrationSuccess:
  metas:
    title: Регистрация

userListSuccess:
  metas:
    title: Список пользователей
  javascripts: [IconBar.js, UserListLoader.js, PopUp.js, main.js]

editUserSuccess:
  metas:
    title: Редактирование пользователя
  javascripts: [IconBar.js, UserListLoader.js, PopUp.js, main.js]

userProfileSuccess:
  metas:
    title: Профиль