logInSuccess:
  metas:
    title: Вход
  layout: layout_without_header

registrationSuccess:
  metas:
    title: Регистрация
  layout: layout_without_header

userListSuccess:
  metas:
    title: Список пользователей