logInSuccess:
  metas:
    title: Вход

registrationSuccess:
  metas:
    title: Регистрация

userListSuccess:
  metas:
    title: Список пользователей
  javascripts: [UserListLoader.js, Popup.js, main.js]

editUserSuccess:
  javascripts: [UserListLoader.js, Popup.js, main.js]