dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: 'true,', details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  propel:
    param: null
    classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=us-cdbr-iron-east-05.cleardb.net;dbname=heroku_a652b928c06e2ac'
      username: b02113edca8db0
      password: 0eb79b64
      encoding: utf8
      persistent: true
      pooling: true
# local mysql mysql:host=localhost;dbname=project;vadim;123vadim
# heroku CLEARDB_DATABASE_URL: mysql://b02113edca8db0:0eb79b64@us-cdbr-iron-east-05.cleardb.net/heroku_a652b928c06e2ac?