dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: 'true,', details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }
test:
  propel:
    param: null
    classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=project'
      username: vadim
      password: 123vadim
      encoding: utf8
      persistent: true
      pooling: true
