propel:
  user: 
    id:    ~
    login: { type: varchar(50), required: true, index: unique } 
    password: { type: varchar(100), required: true } 
    name: { type: varchar(40), required: true } 
    last_name: { type: varchar(50), required: true } 
    role: { type: varchar(10), required: true } 