user: 
  actAs: { Timestampable: ~ } 
  columns: 
    login: { type: string(50), notnull: true, unique: true } 
    password: { type: string(100), notnull: true } 
    name: { type: string(40), notnull: true } 
    last_name: { type: string(50), notnull: true } 
    role: { type: string(10), notnull: true }